# Generated by Django 3.2.7 on 2021-09-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_contact_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phones',
            field=models.JSONField(default={}),
        ),
    ]
