# Generated by Django 3.2.7 on 2021-09-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contact_phones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phones',
            field=models.JSONField(default=dict),
        ),
    ]
