# Generated by Django 3.2.7 on 2021-09-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contact_phones'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='emails',
            field=models.JSONField(default=dict),
        ),
    ]
