# Generated by Django 3.2.7 on 2021-09-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contact_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-firstName']},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phones',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='emails',
            field=models.CharField(default='', max_length=200),
        ),
    ]
