# Generated by Django 3.2.7 on 2021-09-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210909_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='emails',
            new_name='email',
        ),
    ]
