# Generated by Django 3.2.7 on 2021-09-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210910_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organization',
            field=models.CharField(max_length=200),
        ),
    ]
